routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Artisan;
Auth::routes();

Route::namespace('Auth')->prefix('auth')->name('auth.')->group(function () {
    Route::post('/sign-up/validate', 'RegisterController@signupValidation')->name('sign-up.validate');
});

Route::namespace('User')->middleware('language')->group(function () {
    Route::get('/', 'PageController@index')->name('user.home'); 

    Route::get('restaurant/{id}/about', 'RestaurantController@about')->name('user.restaurant.about');

    Route::get('/reviews', 'RestaurantController@reviews')->name('user.restaurant.reviews');

    Route::get('/menu', 'RestaurantController@menu')->name('user.restaurant.menu');

    Route::get('/offers', 'RestaurantController@offers')->name('user.restaurant.offers');

    Route::get('/deals', 'RestaurantController@deals')->name('user.restaurant.deals');

    Route::post('menu/get/items', 'RestaurantController@getMenu')->name('menu.get');

    Route::post('deals-menu-items', 'RestaurantController@getDealsItemByID')->name('user.deals.menu');

    Route::post('offers-menu-items', 'RestaurantController@getOffersItemByID')->name('user.offers.menu');

    Route::post('deal-menu-item-name', 'RestaurantController@getMenuItemNameByDealItemId')->name('user.deal-item.name');

    Route::resource('restaurant', 'RestaurantController');

    Route::get('/language/{locale}', 'PageController@locale')->name('user.locale');

    Route::get('/about-us', 'PageController@about')->name('user.about');

    Route::get('/location', 'PageController@location')->name('user.location');

    Route::get('/blog', 'PageController@blog')->name('user.blog');

    Route::get('/careers', 'PageController@careers')->name('user.careers');

    Route::get('/press', 'PageController@press')->name('user.press');

    Route::get('/faq', 'PageController@faq')->name('user.faq');

    Route::get('/delivery-info', 'PageController@deliveryInfo')->name('user.delivery-info');

    Route::get('/contact-us', 'PageController@contact')->name('user.contact');

    Route::post('/contact/post', 'PageController@postContact')->name('user.contact.post');

    Route::get('/why-eatoeat', 'PageController@why')->name('user.why');

    Route::get('/cancellations-and-refunds', 'PageController@cancellations')->name('user.cancellations');

    Route::get('/terms-and-conditions', 'PageController@terms')->name('user.terms');

    Route::get('/privacy-policy', 'PageController@privacy')->name('user.privacy');

    Route::get('/search', 'PageController@search')->name('user.search');

    Route::get('/landing', 'PageController@landing')->name('admin.landing');

    Route::resource('cuisine', 'CuisineController');

    Route::resource('cart', 'CartController');

    Route::post('/location', 'UserController@location')->name('user.location');

    Route::post('/restaurant/validate-order', 'RestaurantController@validateOrder')->name('user.restaurant.validate-order');

    Route::post('/restaurant/delivery-charge', 'RestaurantController@getDeliveryCharge')->name('user.restaurant.delivery-charge');

    Route::post('/restaurant/validate-takeaway-order', 'RestaurantController@validateTakeawayOrder')->name('user.restaurant.validate-takeaway-order');

    Route::get('contact-thank-you', 'PageController@contactThankYou')->name('contact.thank.you');

    Route::get('reservation-thank-you', 'PageController@reservationThankYou')->name('reservation.thank.you');

    Route::get('user/guest', 'UserController@guest')->name('user.guest');

    Route::post('/subscribe', 'NewsletterController@store')->name('user.subscribe');

    Route::post('branch/pick', 'RestaurantController@pickBranch')->name('branch.pick');
});

Route::get('master-admin/landing', 'MasterAdmin\PageController@landing')->name('master-admin.landing');

Route::namespace('User')->middleware(['auth', 'user', 'language', 'guest_filter'])->group(function () {
    Route::post('/user/favourite', 'UserController@favourite')->name('user.favourite');

    Route::post('/user/favourite-menu-item', 'UserController@favouriteMenuItem')->name('user.favourite-menu-item');

//    Route::get('/user/favourites', 'UserController@favourites')->name('user.favourites');

    Route::get('/user/favourites', 'UserController@menuItemFavourites')->name('user.favourites');

    Route::get('/user/deliveries', 'UserController@deliveries')->name('user.deliveries');

    Route::get('/user/takeaways', 'UserController@takeaways')->name('user.takeaways');

    Route::get('/user/reservations', 'UserController@reservations')->name('user.reservations');

    Route::get('/user/profile', 'UserController@profile')->name('user.profile');

    Route::post('/user/profile/post', 'UserController@profilePost')->name('user.profile.post');

    Route::get('/user/password', 'UserController@password')->name('user.password');

    Route::post('/user/password/post', 'UserController@passwordPost')->name('user.password.post');

    Route::get('/user/dining', 'UserController@dining')->name('user.dining');

    Route::post('/user/dining/post', 'UserController@diningPost')->name('user.dining.post');

    Route::get('/user/communication', 'UserController@communication')->name('user.communication');

    Route::post('/user/communication/post', 'UserController@communicationPost')->name('user.communication.post');

    Route::get('/user/payment', 'UserController@payment')->name('user.payment');

    Route::post('/user/payment/post', 'UserController@paymentPost')->name('user.payment.post');
});
Route::namespace('User')->middleware(['auth', 'user', 'language'])->group(function () { 

    Route::get('/user/address', 'UserController@address')->name('user.address');

    Route::resource('user', 'UserController');

    Route::get('delivery/confirm', 'DeliveryController@confirm')->name('delivery.confirm');

    Route::get('delivery/paypal-success', 'DeliveryController@paypalSuccess')->name('user.delivery.paypal-success');

    Route::get('delivery/paypal-fail', 'DeliveryController@paypalFail')->name('user.delivery.paypal-fail');

    Route::post('delivery/validate', 'DeliveryController@validateDelivery')->name('delivery.validate');

    Route::post('delivery/email', 'DeliveryController@email')->name('delivery.email');

    Route::resource('delivery', 'DeliveryController');

    Route::get('takeaway/confirm', 'TakeawayController@confirm')->name('takeaway.confirm');

    Route::get('takeaway/paypal-success', 'TakeawayController@paypalSuccess')->name('user.takeaway.paypal-success');

    Route::get('takeaway/paypal-fail', 'TakeawayController@paypalFail')->name('user.takeaway.paypal-fail');

    Route::post('takeaway/validate', 'TakeawayController@validateTakeaway')->name('takeaway.validate');

    Route::post('takeaway/email', 'TakeawayController@email')->name('takeaway.email');

    Route::resource('takeaway', 'TakeawayController');

    Route::post('reservation/email', 'ReservationController@email')->name('reservation.email');

    Route::resource('reservation', 'ReservationController');

    Route::post('address/update-all', 'AddressController@updateAddress')->name('address.update.all');

    Route::resource('address', 'AddressController');

    Route::resource('review', 'ReviewController')->only(['store']);

    Route::post('/ticket/user/message', 'TicketController@userMessage')->name('ticket.user.message');

    Route::resource('ticket', 'TicketController');

    Route::post('promotion/validate', 'PromotionController@validatePromocode')->name('promotion.validate');

    Route::resource('promotion', 'PromotionController');
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth', 'admin', 'language'])->group(function () {

    Route::post('delivery/get', 'DeliveryController@getDeliveries')->name('delivery.get');

    Route::resource('delivery', 'DeliveryController');

    Route::post('takeaway/get', 'TakeawayController@getTakeaways')->name('takeaway.get');

    Route::resource('takeaway', 'TakeawayController');

    Route::post('reservation/get', 'ReservationController@getReservations')->name('reservation.get');

    Route::resource('reservation', 'ReservationController');

    Route::post('menu/get', 'MenuController@getMenus')->name('menus.get');

    Route::post('cuisines/get', 'MenuController@getCuisines')->name('cuisines.get');

    Route::post('menu/get/items', 'MenuController@getMenu')->name('menu.get');

    Route::resource('menu', 'MenuController');

    Route::resource('deals', 'DealsController');

    Route::resource('offers', 'OfferController');

    Route::resource('branches', 'BranchController');

    Route::post('branches/get/items', 'BranchController@getBranches')->name('branches.get');

    Route::post('branch/deactive', 'BranchController@deactive')->name('branch.deactive');

    Route::post('deals/get/items', 'DealsController@getDealsItem')->name('deals.get');

    Route::post('offers/get/items', 'OfferController@getOffersItem')->name('offers.get');

    Route::post('offer-item/force-delete', 'OfferController@forceDelete')->name('offer-item.force-delete');

    Route::post('menu-items/get', 'MenuItemController@getMenuItemById')->name('menu-items.get');


app/Http/Controllers/Api/User/CuisineController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Cuisine;
use App\Repository\CuisineRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Class CuisineController
 * @package App\Http\Controllers\Api\User
 */
class CuisineController extends Controller
{
    protected $cuisine;

    /**
     * CuisineController constructor.
     * @param CuisineRepository $cuisine_repository
     */
    public function __construct(CuisineRepository $cuisine_repository)
    {
        $this->cuisine = $cuisine_repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cuisines = $this->cuisine->getPopular();

        foreach ($cuisines as $cuisine) {
            $cuisine->logo = getStorageUrl() . $cuisine->logo;
        }

        return response()->json([
            'message' => 'success',
            'data' => [
                'cuisines' => $cuisines
            ]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function show(Cuisine $cuisine)
    {
        $cuisine->restaurants = $cuisine->restaurants()->get();

        $cuisine->logo = getStorageUrl() . $cuisine->logo;

        foreach ($cuisine->restaurants as $key => $restaurant) {
            $restaurant->reviews = $restaurant->reviews()->get();

            $restaurant->rating = 5;

            $total = 0;

            $restaurant->sort = $key;

            $restaurant->logo = getStorageUrl() . $restaurant->logo;

            if (count($restaurant->reviews)) {
                foreach ($restaurant->reviews as $review) {
                    $total += $review->rating;
                }
                $restaurant->rating = number_format($total / count($restaurant->reviews), 2, '.', '');
            }

        }

        return response()->json([
            'message' => 'success',
            'data' => [
                'cuisine' => $cuisine
            ]
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function edit(Cuisine $cuisine)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cuisine $cuisine)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cuisine $cuisine)
    {
        //
    }
}

app/Http/Controllers/MasterAdmin/CuisineController.php
<?php

namespace App\Http\Controllers\MasterAdmin;

use App\Cuisine;
use App\Http\Controllers\Controller;
use App\Repository\CuisineRepository;
use Illuminate\Http\Request;

/**
 * Class CuisineController
 * @package App\Http\Controllers\MasterAdmin
 */
class CuisineController extends Controller
{
    protected $cuisine;

    /**
     * CuisineController constructor.
     * @param CuisineRepository $cuisine_repository
     */
    public function __construct(CuisineRepository $cuisine_repository)
    {
        $this->cuisine = $cuisine_repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cuisines = $this->cuisine->all();

        foreach ($cuisines as $cuisine) {
            $cuisine->logo = getStorageUrl() . $cuisine->logo;
        }

        return view('master-admin.cuisine.index', [
            'cuisines' => $cuisines
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:cuisines',
            'image' => 'required'
        ]);

        if ($request->image) {
            $path = $request->file('image')->store('cuisine');
            $request->request->set('logo', $path);
        }

        $cuisine = $this->cuisine->create($request->except(['_token', 'image']));

        if ($cuisine) {
            $request->session()->flash('success', 'Saved successfully!');
            return redirect(route('master-admin.cuisine.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function show(Cuisine $cuisine)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function edit(Cuisine $cuisine)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Cuisine $cuisine
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cuisine $cuisine)
    {
        if ($request->image) {
            $path = $request->file('image')->store('cuisine');
            $request->request->set('logo', $path);
        }

        $update = $cuisine->update($request->except(['_token', 'image']));

        if ($update) {
            $request->session()->flash('success', 'Saved successfully!');
            return redirect(route('master-admin.cuisine.index'));
        }
    }

    /**
     * @param Cuisine $cuisine
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Cuisine $cuisine)
    {
        $delete = $cuisine->delete();
        if ($delete) {
            return response()->json([
                'message' => 'success',
                'data' => []
            ]);
        }
    }
}

app/Http/Controllers/MasterAdmin/PageController.php
<?php

namespace App\Http\Controllers\MasterAdmin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

/**
 * Class PageController
 * @package App\Http\Controllers\MasterAdmin
 */
class PageController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function landing()
    {
        if (Auth::check() && Auth::user()->role == 'master_admin') {
            return redirect(route('master-admin.restaurant.request'));
        } else {
            return view('master-admin.page.landing');
        }
    }
}

resources/views/master-admin/cuisine/index.blade.php
@extends('layouts.master-admin')

@section('content')

    <div class="row">
        <div class="panel with-nav-tabs panel-default">
            <div class="panel-heading single-project-nav">
                @include('includes.master-admin-platform-header',['active'=>'cuisine'])
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="cuisines">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="post-code-form">
                                    <div>
                                        <h4>Cuisine Types</h4>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <form action="{{route('master-admin.cuisine.store')}}"
                                                          method="post" enctype="multipart/form-data">
                                                        @csrf
                                                        <div
                                                            class="col-md-4 col-sm-4 form-group @if($errors->has('name')) has-error @endif">
                                                            <input type="text" class="form-control" name="name"
                                                                   placeholder="Enter Cuisine">
                                                            @if($errors->has('name'))
                                                                <span class="help-block">
                                                                    {{$errors->first('name')}}
                                                                </span>
                                                            @endif
                                                        </div>
                                                        <div class="col-sm-2 form-group" id="image-preview-wrapper"
                                                             style="display: none;">
                                                            <img src="" alt="" class="img-responsive" id="image-preview"
                                                                 style="display: none;">
                                                        </div>
                                                        <div
                                                            class="col-md-4 col-sm-4 form-group @if($errors->has('image')) has-error @endif">
                                                            <input type="file" class="form-control" name="image"
                                                                   id="image-file"
                                                                   placeholder="Enter Cuisine Image">
                                                            <p class="help-block">Max filesize: 1MB</p>
                                                            @if($errors->has('image'))
                                                                <span class="help-block">
                                                                    {{$errors->first('image')}}
                                                                </span>
                                                            @endif
                                                        </div>
                                                        <div class="col-md-2 col-sm-2">
                                                            <input type="submit" class="btn btn-add-post"
                                                                   value="Add Cuisine +  ">
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row cuisine-lists-row">
                            @foreach($cuisines as $cuisine)
                                <div class="col-md-2 col-sm-3 cuisine-block">
                                    <img src="{{ asset('storage/'.$cuisine->logo) }}" alt="" class="img-responsive"
                                         style="object-fit: cover;width: 100%;">
                                    <div class="cuisine-lists">
                                        <a href="#" onclick="deleteCuisine('{{$cuisine->id}}')">
                                            <div class="rect"></div>
                                        </a>
                                        <p><a href="#"
                                              onclick="updateCuisine({{$cuisine->id}})">{{$cuisine->name}}</a>
                                        </p>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="edit-cuisine-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Edit Cuisine</h4>
                </div>
                <form id="update-cuisine-form" action="{{route('cuisine.index')}}" enctype="multipart/form-data"
                      method="post">
                    @method('put')
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="name">Cuisine Name</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Enter Cuisine">
                        </div>
                        <div class="form-group">
                            <label for="Image">Image</label>
                            <img src="" alt="" class="img-responsive" id="preview" style="display: none;">
                            <input type="file" class="form-control" name="image" id="image"
                                   placeholder="Enter Cuisine Image">
                            <p class="help-block">Max filesize: 1MB</p>
                            <p class="help-block">Enter Cuisine Image</p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript">

        let cuisines = {!! json_encode($cuisines) !!};

        function deleteCuisine(cuisine_id) {
            var confirm = window.confirm('Are you sure you want to delete this cuisine?');

            if (confirm) {
                axios.delete('{{route('master-admin.cuisine.index')}}/' + cuisine_id)
                    .then(function (response) {
                        if (response.data.message == 'success') {
                            $.alert({title: 'Success!', content: 'Deleted Successfully!', theme: 'success'});
                            window.location.reload();
                        }
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
            }
        }

        function updateCuisine(cuisine_id) {
            let selected_cuisine = cuisines.filter(function (cuisine) {
                return cuisine.id == cuisine_id
            });
            cuisine = selected_cuisine[0];
            document.getElementById('name').value = cuisine.name;
            document.getElementById('update-cuisine-form').action = '{{route('master-admin.cuisine.index')}}/' + cuisine.id;
            jQuery('#edit-cuisine-modal').modal('show');
        }

        window.addEventListener('load', function () {
            jQuery('.cuisine-block img').each(function (cuisine) {
                jQuery(this).height(jQuery(this).width());
            });
        });

        document.querySelector('#image-file').addEventListener('change', function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    document.querySelector('#image-preview').setAttribute('src', e.target.result);
                    document.querySelector('#image-preview').style.display = 'block';
                    document.querySelector('#image-preview-wrapper').style.display = 'block';
                };

                reader.readAsDataURL(this.files[0]);
            }
        });

        document.querySelector('#image').addEventListener('change', function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    document.querySelector('#preview').setAttribute('src', e.target.result);
                    document.querySelector('#preview').style.display = 'block';
                };

                reader.readAsDataURL(this.files[0]);
            }
        });
    </script>

@endsection